# These are supported funding model platforms

github: [tamojit-123]
patreon: Tamojit Das
open_collective: tamojit-das
ko_fi: tamojit
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://developersportfolio.netlify.app
